# Generated by Django 5.0.1 on 2024-01-03 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_category_name_contact_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
